[build]
  publish = "dist"  # Using dist as the publish directory since that's where our static files are

# Redirect rule for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false   # Don't force redirect for existing files

# Asset handling
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
